### ISSUE TITLE
Cannot reach Build Menu

### ISSUE THREAD

**Issue by SwarupRDas** [slrwin/sunnyrepo#2]
Cannot Reach the BUILD MENU Option

![Sunny1](https://github.com/slrwin/sunnyrepo/assets/121832042/7f0d2cc1-7b30-4ae4-98e4-5253c728af53)

**Comment by SwarupRDas** [comment]
@slrwin Could you provide a solution pl?

**Comment by slrwin** [comment]
Which version of kodi you are using?

**Comment by SwarupRDas** [comment]
@slrwin Kodi version 20

**Comment by slrwin** [comment]
> @slrwin Kodi version 20

 V20 is not supported on this build anymore, please use v21 beta 2 to use the build.

**Comment by SwarupRDas** [comment]
@slrwin  Got you, Thanks

**Comment by SwarupRDas** [comment]
Hi, Upgraded to  v21 beta 2 and still cannot get to the build menu

BTW 

DO I have to uncheck everything on this screen?

Some buttoned are checked.
![image](https://github.com/slrwin/sunnyrepo/assets/121832042/356d1166-b9c3-40cc-84fd-e6f37a51fbdd)

**Comment by slrwin** [comment]
> Hi, Upgraded to v21 beta 2 and still cannot get to the build menu
> 
> BTW
> 
> DO I have to uncheck everything on this screen?
> 
> Some buttoned are checked. ![image](https://private-user-images.githubusercontent.com/121832042/299454563-356d1166-b9c3-40cc-84fd-e6f37a51fbdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzE0ODksIm5iZiI6MTcwNjEzMTE4OSwicGF0aCI6Ii8xMjE4MzIwNDIvMjk5NDU0NTYzLTM1NmQxMTY2LWI5YzMtNDBjYy04NGZkLWU2ZjM3YTUxZmJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQyMTE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWYxNDc4NjdiNzE3Y2U3ODhjODFiNDkxMzMzM2M3YjczYWRlNDFlNWNmYTQxZDhlNWI0YzRlNDc0Y2RhMWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Bzxf45T3AL-ALoklEHgUdRxucfCnJ-I8TKnbJVWfn0)

Select continue button on this screen.

Or you can cancel this window and open the addon to navigate to build options.  Please go through the steps in video on my repo page.

**Comment by SwarupRDas** [comment]
How do I go from this Screen? I cannot download anything after the continue button.
![IMG_4048](https://github.com/slrwin/sunnyrepo/assets/121832042/929b4eac-3a88-409d-8c6c-0f1142ed1aa7)
![IMG_4047](https://github.com/slrwin/sunnyrepo/assets/121832042/4b98e0aa-ca49-4806-9d62-1c5765b7ac14)

**Comment by slrwin** [comment]
From settings window you can't go to build options. Open the addon directly and then navigate to build options. If build menu screen is displayed press backspace in laptop to close it.
