### ISSUE TITLE
Gettinh could not connect to repositorh on 2.0.4 repositoru version

### ISSUE THREAD

**Issue by prakashkvau** [slrwin/sunnyrepo#3]
When try to install from repository, I get an error that it cannot connect to the repository

**Comment by slrwin** [comment]
There is no issue with the repository. Retry again, also check whether Github is accessible from your device, if not use a VPN to connect to repo.

**Comment by prakashkvau** [comment]
I can connect to github and download the repository, but when I run the install from repository, is throws an error.
![2024-02-19-18-54-39-003](https://github.com/slrwin/sunnyrepo/assets/4746621/1cdd1bd2-027f-42a8-826a-c5771088c08c)

**Comment by slrwin** [comment]
I will redeploy the repo zip, try to update it from repo URL and see if it works.

**Comment by slrwin** [comment]
Repository connection issue is fixed now.
